# Generated by Django 3.1.4 on 2021-01-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20210103_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='to_do_completed',
            field=models.BooleanField(default=False),
        ),
    ]
