# Generated by Django 3.1.5 on 2021-01-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todocontainer_todos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocontainer',
            name='todos_description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
    ]
