# Generated by Django 3.1.5 on 2021-01-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210114_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/uploads/avatars/person-icon.png', null=True, upload_to='avatars'),
        ),
    ]
