# Generated by Django 3.1.5 on 2021-01-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210114_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friends',
            new_name='followers',
        ),
    ]
