# Generated by Django 3.1.5 on 2021-01-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210114_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_project_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_project_tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
