# Generated by Django 3.1.5 on 2021-01-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210115_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_project_description',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_project_name',
            field=models.CharField(default='No Project Name', max_length=50),
        ),
    ]
